//! Shared types for AudioMaster.
//!
//! This module defines all the data types used across the mastering pipeline,
//! including audio analysis results, mastering parameters, and configuration types.

use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// Metadata about an audio file.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AudioMetadata {
    /// Absolute path to the audio file.
    pub path: PathBuf,
    /// Sample rate in Hz (e.g., 44100, 48000).
    pub sample_rate: u32,
    /// Number of audio channels (1 = mono, 2 = stereo).
    pub channels: u16,
    /// Duration in seconds.
    pub duration_secs: f64,
    /// Bit depth if known (e.g., 16, 24).
    pub bit_depth: Option<u16>,
    /// File format (e.g., "WAV", "FLAC", "MP3").
    pub format: String,
}

/// Complete audio analysis results.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AudioAnalysis {
    /// File metadata.
    pub metadata: AudioMetadata,
    /// Integrated loudness in LUFS (EBU R128).
    pub lufs_integrated: f64,
    /// Maximum short-term loudness (3-second window) in LUFS.
    pub lufs_short_term_max: f64,
    /// RMS level in dB.
    pub rms_db: f64,
    /// Sample peak level in dB.
    pub peak_db: f64,
    /// True peak level (inter-sample) in dB.
    pub true_peak_db: f64,
    /// Dynamic range in dB (difference between loud and quiet sections).
    pub dynamic_range_db: f64,
    /// Stereo width (0.0 = mono, 1.0 = full stereo).
    pub stereo_width: f64,
    /// 7-band frequency analysis.
    pub frequency_bands: FrequencyBands,
}

/// 7-band frequency analysis results (all in dB).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FrequencyBands {
    /// Sub-bass (20–60 Hz).
    pub sub_bass: f64,
    /// Bass (60–250 Hz).
    pub bass: f64,
    /// Low-mid (250–500 Hz).
    pub low_mid: f64,
    /// Mid (500–2000 Hz).
    pub mid: f64,
    /// Upper-mid (2000–4000 Hz).
    pub upper_mid: f64,
    /// Presence (4000–6000 Hz).
    pub presence: f64,
    /// Brilliance (6000–20000 Hz).
    pub brilliance: f64,
}

/// Mastering parameters generated by AI or manual configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MasteringParams {
    pub eq: Vec<EqBand>,
    pub compression: CompressionParams,
    pub limiter: LimiterParams,
    pub stereo: StereoParams,
    pub target_lufs: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EqBand {
    pub frequency: f64,
    pub gain_db: f64,
    pub q: f64,
    pub band_type: EqBandType,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EqBandType {
    LowShelf,
    HighShelf,
    Peak,
    LowPass,
    HighPass,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompressionParams {
    pub threshold_db: f64,
    pub ratio: f64,
    pub attack_ms: f64,
    pub release_ms: f64,
    pub knee_db: f64,
    pub makeup_gain_db: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LimiterParams {
    pub enabled: bool,
    pub ceiling_db: f64,
    pub release_ms: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StereoParams {
    pub width: f64,
    pub balance: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MasteringResult {
    pub output_path: PathBuf,
    pub backend_used: String,
    pub pre_analysis: Option<AudioAnalysis>,
    pub post_analysis: Option<AudioAnalysis>,
    pub params_applied: Option<MasteringParams>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Backend {
    Auto,
    Matchering,
    Ai,
    LocalMl,
}

impl std::fmt::Display for Backend {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Backend::Auto => write!(f, "auto"),
            Backend::Matchering => write!(f, "matchering"),
            Backend::Ai => write!(f, "ai"),
            Backend::LocalMl => write!(f, "local-ml"),
        }
    }
}

impl std::str::FromStr for Backend {
    type Err = anyhow::Error;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "auto" => Ok(Backend::Auto),
            "matchering" => Ok(Backend::Matchering),
            "ai" => Ok(Backend::Ai),
            "local-ml" | "local_ml" | "localml" => Ok(Backend::LocalMl),
            _ => anyhow::bail!("Unknown backend: {s}"),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AiProvider {
    Ollama,
    KeyhanStudio,
    OpenAi,
    Anthropic,
}

impl std::fmt::Display for AiProvider {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AiProvider::Ollama => write!(f, "ollama"),
            AiProvider::KeyhanStudio => write!(f, "keyhanstudio"),
            AiProvider::OpenAi => write!(f, "openai"),
            AiProvider::Anthropic => write!(f, "anthropic"),
        }
    }
}

impl std::str::FromStr for AiProvider {
    type Err = anyhow::Error;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "ollama" => Ok(AiProvider::Ollama),
            "keyhanstudio" | "keyhan" => Ok(AiProvider::KeyhanStudio),
            "openai" => Ok(AiProvider::OpenAi),
            "anthropic" | "claude" => Ok(AiProvider::Anthropic),
            _ => anyhow::bail!("Unknown AI provider: {s}"),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AudioFormat {
    Wav,
    Flac,
    Mp3,
}

impl std::fmt::Display for AudioFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AudioFormat::Wav => write!(f, "wav"),
            AudioFormat::Flac => write!(f, "flac"),
            AudioFormat::Mp3 => write!(f, "mp3"),
        }
    }
}

impl std::str::FromStr for AudioFormat {
    type Err = anyhow::Error;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "wav" => Ok(AudioFormat::Wav),
            "flac" => Ok(AudioFormat::Flac),
            "mp3" => Ok(AudioFormat::Mp3),
            _ => anyhow::bail!("Unknown audio format: {s}"),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Preset {
    Streaming,
    Cd,
    Vinyl,
    Loud,
}

impl Preset {
    pub fn target_lufs(&self) -> f64 {
        match self {
            Preset::Streaming => -14.0,
            Preset::Cd => -9.0,
            Preset::Vinyl => -12.0,
            Preset::Loud => -6.0,
        }
    }

    pub fn description(&self) -> &'static str {
        match self {
            Preset::Streaming => "Optimized for streaming platforms (-14 LUFS)",
            Preset::Cd => "CD-level loudness (-9 LUFS)",
            Preset::Vinyl => "Vinyl-friendly dynamics (-12 LUFS)",
            Preset::Loud => "Maximum loudness (-6 LUFS)",
        }
    }
}

impl std::fmt::Display for Preset {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Preset::Streaming => write!(f, "streaming"),
            Preset::Cd => write!(f, "cd"),
            Preset::Vinyl => write!(f, "vinyl"),
            Preset::Loud => write!(f, "loud"),
        }
    }
}

impl std::str::FromStr for Preset {
    type Err = anyhow::Error;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "streaming" => Ok(Preset::Streaming),
            "cd" => Ok(Preset::Cd),
            "vinyl" => Ok(Preset::Vinyl),
            "loud" => Ok(Preset::Loud),
            _ => anyhow::bail!("Unknown preset: {s}. Available: streaming, cd, vinyl, loud"),
        }
    }
}
